{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-data" (include "cluster-lite-wiki.fullname" .)) .Values.persistence.volumeName }}
  labels:
    {{- include "cluster-lite-wiki.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- else if .Values.persistence.hostPath }}
  storageClassName: ""
  {{- end }}
  {{- if .Values.persistence.hostPath }}
  volumeName: {{ default (printf "%s-data" (include "cluster-lite-wiki.fullname" .)) .Values.persistence.volumeName }}
  {{- end }}
{{- end }}
