{{- if and .Values.persistence.enabled .Values.persistence.hostPath (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default (printf "%s-data" (include "cluster-lite-wiki.fullname" .)) .Values.persistence.volumeName }}
  labels:
    {{- include "cluster-lite-wiki.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
    type: DirectoryOrCreate
{{- end }}
